-- User configuration file
-- This is your personal Neovim configuration
-- The system will load this first, then add its own configuration on top
--
-- Example configurations:
-- vim.g.mapleader = ' '          -- Set space as leader key
-- vim.opt.number = true         -- Show line numbers
-- vim.opt.relativenumber = true -- Show relative line numbers
--
-- Add your custom keymaps, settings, and plugins here
